### ISSUE TITLE
HLS-VI: Additional contracts drafted

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-Project-Actions#12]
```[tasklist]
### Tasks
- [x] DAAC selection form for ESD
- [x] Software Architecture Diagram
- [x] Interface Control Document
```
