### ISSUE TITLE
HLS-VI: Formulation to Implementation Decision Gate

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-Project-Actions#16]
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/19
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/20
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/18
```

**Comment by CherrelleTucker** [comment]
- [ ] Action: SNWG SEP - follow up with ESDS re: open meetings, determine how to handle meeting notes so that they are 1) openly available and 2) discoverable.
- [ ] Action: John Mandel update budget numbers in project plan (Section 2.4).
- [ ] Action: SNWG MO & HLS-VI team to follow up on potential handoff to USGS and expand that section in the project plan (Section 3.3), and/or expand on other handoff options.
- [ ] Action: LP.DAAC to review and provide feedback to the HLS-VI team and SNWG MO on the Open Science Data Management Plan (Section 4.2.1 in the project plan) within 1 month.
- [ ] Action: SNWG MO to follow up with ESDIS re: DAAC selection memo “additional instructions” detailed work plan to be delivered 90 days after the memo.
- [ ] Action: LP.DAAC/ESDIS - identify and communicate to SNWG MO the expected timeline for the Interface Control Document (ICD) with LP.DAAC.
- [x] Action: ESDIS determine whether an Inter-Project Agreement (IPA), or any other form of agreement/documentation is needed in addition to the DAAC ICD.
- [x] Action: Jeanne' le Roux Link HLS-VI risk register to the prime project risk registers (done).
- [ ] Action: John Mandel to review mitigation actions that are dependent upon external parties. Document the timeline of working through closing the risk or that the other party has accepted responsibility for a portion of that risk.

**Comment by CherrelleTucker** [comment]
From: Ostrenga, Dana M. (GSFC-4230) <dana.ostrenga@nasa.gov> 
Sent: Friday, September 8, 2023 10:41 AM
To: le Roux, Jeanné (MSFC-ST11)[UAH] <jeanne.leroux@nasa.gov>; Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services] <cherrelle.j.tucker@nasa.gov>; Gregory, Sean P. (MSFC-ST14) <sean.p.gregory@nasa.gov>
Cc: Albers, Cerese {HQ} (MSFC-DK000) <cerese.m.albers@nasa.gov>
Subject: Action follow-up

Hello Sean, Jeanné, and Cherrelle,

I wanted to follow-up from our meeting yesterday on the action to confirm required documents with ESDIS. We will only need an ICD.

Also, is there any way to share any of the slides from yesterday for internal purposes?

Best,
Dana
