### ISSUE TITLE
PBL: Preliminary Project Plan/Proposal Delivery & Review (iterative updates)

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-Project-Actions#26]
The solution project lead(s) notifies the SNWG MO PM that the [preliminary Project Plan/proposal](https://docs.google.com/document/d/1hfbKXOta7htTs1RDtvpAXxBwu6QxuqnndGXOMkyM-UQ/edit) is ready for review. The SNWG MO reviews the document internally and requests feedback/iterates until the information needed to proceed to the ATP DG and is ready to be placed under contract/agreement.

- The SNWG MO PM is responsible for collecting all feedback and communicating it back to the solution project lead(s) in a timely manner
- The iterative negotiations continue until the SNWG MO PM determines the preliminary Project Plan/proposal contains the information needed to proceed to the ATP DG and is ready to be placed under contract/agreement.
- [ ] The SNWG MO will hold an internal review of the preliminary Project Plan/proposal (SNWG MO PM, Assistant PM, PS, Deputy PS, SE)
    - [ ] ATP DG Checklist (see Table 1)
    - [ ] Included in the preliminary Project Plan/proposal, the solution project lead(s) provides the following to the SNWG MO PM (per the Project Plan Template instructions):
        - [ ] Project background information
        - [ ] Notional Schedule/Milestones & tasks
        - [ ] Personnel/org chart, roles/responsibilities
        - [ ] High-level WBS (optional)
        - [ ] High fidelity Budget (Cost Estimate)
        - [ ] Project Requirements
            - Note: Solution Projects may need help deriving these, the SNWG MO SE can assist
        - [ ] Notional Open Source Data Management Plan (OSDMP) (SNWG MO should provide an example/expectations per ESDIS)
- The SNWG MO provides the following to the solution project lead(s) and must be agreed upon:
    - [ ] Agreement to adhere to the SNWG MO Program Level Requirements (PLRs) and any exceptions documented with a rationale (PLR compliance matrix)
    - [ ]         Open Source Science (OSS) expectations:
    - [ ]         The solution project should list project-specific OSS objectives in the preliminary Project Plan/proposal
    - [ ]         Intent to participate in and contribute content to the SEP
    - [ ]         Agreed upon project milestone reviews
    - [ ]         Any identified risks and initial risk registry
