### ISSUE TITLE
HLS-VI:FY23 Q1

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-Project-Actions#6]
```[tasklist]
### Tasks
- [x] Complete onboarding
- [x] Establish team
- [x] determine outputs and formats
- [x] draft project plan
- [ ] draft open science data management plan (OSDMP)
```
