### ISSUE TITLE
Formulation: HLS-VI 

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-Project-Actions#7]
```[tasklist]
### Deliverables
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/11
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/9
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/10
```

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/13
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/12
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/14
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/16
- [ ] https://github.com/NASA-IMPACT/SNWG-MO-Project-Actions/issues/15
```

Reference: https://docs.google.com/document/d/1tcVTcJdkap0UZE7MhemKnVNKbCgcQEpZKO-LrYg2K7w/edit?usp=share_link
